### ISSUE TITLE
plugin naming

### ISSUE THREAD

**Issue by hgschmie** [HubSpot/dependency-management-maven-plugin#1]
Hi,

the Apache Maven project has a plugin development guide at https://maven.apache.org/guides/plugin/guide-java-plugin-development.html and they suggest to name a plugin xxx-maven-plugin. 

Any chance to rename this plugin to dependency-management-maven-plugin for a 1.0 release?

**Comment by jhaber** [comment]
Sure thing, I can rename the repo as well.

**Comment by jhaber** [comment]
3eda0cdf3e7c6fe923059f05f52bb41c4d1fa973

**Comment by jhaber** [comment]
I made a 0.5 release with this change, let me know if you have any other thoughts on the plugin!
